serverHost: localhost
serverPort: 9999

brokerHost: localhost
brokerPort: 8888

carAddresses:
  - http://localhost:8080
  - http://localhost:8081
  - http://localhost:8082
  - http://localhost:8083

schedulerInterval: 5